### PR TITLE
Enable usage in check mode by forcing execution of pre-checks

### PR DESCRIPTION
**Pull request by mraerino**
I just tried to use this rule with `--check` in a playbook and encountered errors because the results of the prechecks were not available.
This change will make it possible to use the role in `check-mode`.

### CODE REVIEW

**Comment by elliotweiser** [comment]
Thanks for the contribution!

Sounds like it's time to drop support for 2.1 and below... You'll need to remove those test cases from the `.travis.yml`. I can review/approve once that's done.

This reminds me to test against 2.4... Thanks for that!

**Comment by mraerino** [comment]
The build failed because it got auto-terminated. Do you know why it could take that long?
Looks like the playbook finished fine.

**Comment by elliotweiser** [comment]
Unfortunately, Travis CI's Mac OS executors can get a bit... tired. In my observation, there's a fair amount of resource contention, and so sometimes it take a LONG TIME to download the command-line-tools. If it takes long enough, Travis will just kill the job.

I kicked the job that failed. Should work this time around 👍 

Turns out the `meta/main.yml` will need to be updated as well, to account for dropped support for 2.1 and below. I can do that it a separate change before releasing the next version.

**Comment by mraerino** [comment]
So is there anything left for me to do or is this PR fine now?

**Pull request merged**
